arch: arm64
default:
  image:
    arm64:
      repository: ghcr.io/singularity-data/risingwave-${ARCH}
      tag: ${ARCH}
    amd64:
      repository: ghcr.io/singularity-data/risingwave
      tag: ${ARCH}
  pullPolicy: IfNotPresent
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1000m
    memory: 2000Mi
  replicas: 1
metaNode:
  requests:
    cpu: 200m
    memory: 1000Mi
  limits:
    cpu: 1000m
    memory: 2000Mi
  replicas: 2
computeNode:
  requests:
    cpu: 200m
    memory: 2000Mi
  limits:
    cpu: 1000m
    memory: 2000Mi
minIO:
  image:
    arm64:
      repository: 639303875316.dkr.ecr.ap-southeast-1.amazonaws.com/risingwave-minio
      tag: ${arch}
    amd64:
      repository: 639303875316.dkr.ecr.ap-southeast-1.amazonaws.com/risingwave-minio
      tag: ${arch}
frontend:
  image:
    arm64:
      repository: 639303875316.dkr.ecr.ap-southeast-1.amazonaws.com/risingwave-frontend
      tag: ${ARCH}-001
    amd64:
      repository: 639303875316.dkr.ecr.ap-southeast-1.amazonaws.com/risingwave-frontend
      tag: ${ARCH}-001


